/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import BusinessEntity.Cliente;
import Services.BoletaManager;
import javax.swing.JOptionPane;

/**
 *
 * @author Fabricio
 */
public class ProductoGUI extends javax.swing.JFrame {

     private BoletaManager manager;
    private Cliente cliente;
    
    /**
     * Creates new form ProductoGUI
     */
 public ProductoGUI(BoletaManager manager, Cliente cliente) {
        this.manager = manager;
        this.cliente = cliente;
        initComponents();
        setTitle("Agregar productos - Cliente: " + cliente.getCliente_nombre());
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtIdProducto = new javax.swing.JTextField();
        txtCantidad = new javax.swing.JTextField();
        btnAgregarProducto = new javax.swing.JButton();
        btnContinuarPago = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaCarrito = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("ID del producto");

        jLabel2.setText("cantidad ");

        jLabel3.setText("Mensaje");

        txtIdProducto.setText("jTextField1");

        txtCantidad.setText("jTextField2");

        btnAgregarProducto.setText("Agregar");
        btnAgregarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarProductoActionPerformed(evt);
            }
        });

        btnContinuarPago.setText("Siguiente");
        btnContinuarPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinuarPagoActionPerformed(evt);
            }
        });

        areaCarrito.setColumns(20);
        areaCarrito.setRows(5);
        jScrollPane1.setViewportView(areaCarrito);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 155, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtIdProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(113, 113, 113))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnContinuarPago)
                .addGap(45, 45, 45))
            .addGroup(layout.createSequentialGroup()
                .addGap(183, 183, 183)
                .addComponent(btnAgregarProducto)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtIdProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnAgregarProducto)
                .addGap(26, 26, 26)
                .addComponent(btnContinuarPago)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarProductoActionPerformed
        String id = txtIdProducto.getText().trim();
String cantidadStr = txtCantidad.getText().trim();

if (id.isEmpty() || cantidadStr.isEmpty()) {
    JOptionPane.showMessageDialog(this, "Completa ambos campos.");
    return;
}

try {
    int cantidad = Integer.parseInt(cantidadStr);
    boolean agregado = manager.agregarProducto(id, cantidad);
    if (agregado) {
        areaCarrito.append("Producto ID " + id + " x" + cantidad + " agregado\n");
        txtIdProducto.setText("");
        txtCantidad.setText("");
    } else {
        JOptionPane.showMessageDialog(this, "Producto no encontrado o sin stock.");
    }
} catch (NumberFormatException ex) {
    JOptionPane.showMessageDialog(this, "Cantidad inválida.");
}
    }//GEN-LAST:event_btnAgregarProductoActionPerformed

    private void btnContinuarPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinuarPagoActionPerformed
      JOptionPane.showMessageDialog(this, "Aquí iría la interfaz de pago.");
// new PagoGUI(manager, cliente).setVisible(true);
// this.dispose();
    }//GEN-LAST:event_btnContinuarPagoActionPerformed

       

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaCarrito;
    private javax.swing.JButton btnAgregarProducto;
    private javax.swing.JButton btnContinuarPago;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtIdProducto;
    // End of variables declaration//GEN-END:variables
}
